version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_EXPOSE}:5432"
    env_file:
      - ./.env
    networks:
      - app

networks:
  app:

volumes:
  app_data:
  node_modules:
